

# Konfiguracja po??czenia z PostgreSQL 18.4.1
spring.datasource.url=jdbc:postgresql://localhost:5432/wypozyczalniasr_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver



# Automatyczne tworzenie/aktualizacja tabel w bazie na podstawie klas Java (Hibernate)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

# Klucz do zewnetrznego API (heigit.org) do kalkulacji drogi

routing.api.key=${ROUTING_API_KEY:default_fake_key_for_github}
routing.depot.latitude=50.04132
routing.depot.longitude=21.99901
routing.cost.per.km=8.0