# serwer na porcie HTTPS
server.port=8443

# Konfiguracja polaczenia z PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/wypozyczalniasr_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/rental_db}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

#Kongiguracja SSL/HTTPS
server.ssl.enabled=true
server.ssl.key-store=Cert/keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=mehow2k
server.ssl.key-store-password=password

# Automatyczne tworzenie/aktualizacja tabel w bazie na podstawie klas Java (Hibernate)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

#poziom logowania
logging.level.root=INFO

#Klucz do tokenu JWT
jwt.secret=${JWT_SECRET}

# Klucz do zewnetrznego API (heigit.org - OpenRouteService) do kalkulacji drogi
routing.api.key=${ROUTING_API_KEY}
routing.depot.latitude=50.04132
routing.depot.longitude=21.99901
routing.cost.per.km=8.0